# Overlay region US-Est (cluster dedie, ex : us-east1 / us-east-1).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: game-server-config
    patch: |
      - op: replace
        path: /data/NEON_REGION
        value: "us-east"
  - target:
      kind: Deployment
      name: game-server
    patch: |
      - op: add
        path: /spec/template/metadata/labels/topology.kubernetes.io~1region
        value: "us-east"
  - target:
      kind: Ingress
      name: game-server
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "us.neon-beat.app"
      - op: replace
        path: /spec/rules/0/host
        value: "us.neon-beat.app"
