apiVersion: v1
kind: Service
metadata:
  name: lobby
  namespace: neon-game
  labels:
    app.kubernetes.io/name: lobby
    app.kubernetes.io/part-of: neon-beat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lobby
  ports:
    - name: http
      port: 80
      targetPort: http
